### ISSUE TITLE
Support text shaping

### ISSUE THREAD

**Issue by alcinnz** [schell/typograffiti#11]
Depending on the alphabet used, this is either a necessity or a nicity.

Modern fontfiles split a high-level concept of "characters" (how humans understand the text) from a low-level concept of "glyphs" (which may be impacted by text wrapping) which actually gets rendered. Whilst for monospace ASCII (maybe Latin1, depending on fontfile) text this is a trivial transformation, a pre-processing pass is required for e.g. Arabic which is currently lacking in Typograffiti.

I propose Typograffiti integrates [Harfbuzz](https://harfbuzz.github.io/) (there's [Haskell bindings](https://hackage.haskell.org/package/gi-harfbuzz) already) into it's internal implementation of it's highlevel API, whilst exposing lower-level APIs a seperate text-wrapping API can use. Specifically Harfbuzz's central function to call is [shape](https://hackage.haskell.org/package/gi-harfbuzz-0.0.5/docs/GI-HarfBuzz-Functions.html#g:method:shape).

**Comment by alcinnz** [comment]
I'm preparing to tackle this issue now, and here's a good page to guide architectural decisions regarding HarfBuzz integration: https://harfbuzz.github.io/what-harfbuzz-doesnt-do.html
I suggest leaving situations where text style changes in the middle of a paragraph to be handled by the text wrapping library.
Specifically we'll need to integrate HarfBuzz inbetween `loadText` & `arDraw`.

I'm very tempted to write my own more-functional HarfBuzz bindings, because that could really help implementing that text wrapping library & hopefully improve threadsafety. Doing that now...

**Comment by alcinnz** [comment]
I wrote my own HarfBuzz language bindings to use which is nicer to use in Haskell. Probably won't make a big difference for Typograffiti directly over the GNOME-generated bindings, but it will for a text-layout module!

https://git.adrian.geek.nz/harfbuzz-pure

It appears to be working well, but hard to check it's output without feed it into something like Typograffiti. So I think I'll start the integration shortly!

**Comment by schell** [comment]
That sounds great! You're really rocking!

**Comment by alcinnz** [comment]
Hmmm, assessing what changes need to be made I think I'll #14 first to make this easier to test...

It looks like it should be reasonably easy to implement the higherlevel API within the existing structure, so I'll tackle that first (alter `makeCharQuad`/`stringTris` to take offset positions, provide alternative to `makeDefaultAllocateWord`). But introducing a lowerlevel API a text wrapping library would require needs minor infrastructural changes (have `defaultAllocateWord` accept HarfBuzz's output rather than input).

**Comment by alcinnz** [comment]
From my current testing it either appears that non-latinate alphabets are totally dependant upon shaping for digital rendering, or I need a more comprehensive fontfile to test against... One that covers more than Latin1!

I think I'll test against Ubuntu to be safe.

**Comment by alcinnz** [comment]
Sorry for the wait, I have a few subprojects I'm juggling.

I've ended up reimplementing everything in the "refactor" branch, adding most of your optimizations back in whilst making sure the low-level APIs expose what I need for full richtext rendering. Though I did end up dropping the word cache. How does it look to you? Would you be happy to publish it to Hackage as a new version of Typograffiti? Any changes you want made?

We could bring the word-cache back within the code I added for handling tabs & newlines, but I wasn't all that keen in putting too much effort into a basic text layout engine. It is a question how fancy we want Typograffiti's built-in text-layout to be to cover 80% of the usecases as I (with some help I've contracted via NLnet funding) the remaining 20%?

I put some effort into providing a nice high-level API, though using the formatting capabilities does require an understanding of the font you're loading. I threw in support for synthetic italics (obliques) since that's a simple matrix transform, amongst several other ways of achieving italics depending on how the font exposes them. I don't have synthetic bold, but if the font exposes it...

If the font exposes OpenType fontfeatures those can be applied to slices of the rendered text, though I haven't tested whether that comes through accurately.

Thoughts?

P.S. I see your profile indicates you're in Nelson now? I'd enjoy meeting in-person!

**Comment by alcinnz** [comment]
P.P.S. The newer language were easier to work with, no need to add utility functions to lesser the pain.

**Comment by schell** [comment]
> with some help I've contracted via NLnet funding

Wow, that's amazing! 

> Any changes you want made? ... Thoughts?

Honestly it's been so long since I worked on this project that I think you have more context than I do at the moment! I'm fine to let you take it wherever you like. Have I not given you hackage credentials yet? I think if you're ready to release I'll give you the keys and let you "take the wheel".

> P.S. I see your profile indicates you're in Nelson now? I'd enjoy meeting in-person!

What a cool coincidence! Let's definitely meet in person. All my contacts are [here](https://zyghost.com/contact/index.html).

**Comment by alcinnz** [comment]
No, you haven't givenme the Hackage credentials. I would appreciate that!

I'll send you an email so you can give me them there, and schedule a meetup!

I guess then I'll put this project under my "Argonaut Stack" column on my site rather than "Argonaut Friends"...

**Comment by alcinnz** [comment]
This is the main addition in the "fancy" branch
