### ISSUE TITLE
Support text directions other than left-to-right

### ISSUE THREAD

**Issue by alcinnz** [schell/typograffiti#12]
Not all languages are written left-to-right, though most are written horizontally. Some are written top-to-bottom. Then you have Japanese where each paragraph can be written either horizontally or vertically, this may impact the API we wish to expose for this.

As is Typograffiti only supports left-to-right text. I'm not sure whether or not a shapping pass would handle this for us...

- [ ] support mixing left-to-right & right-to-left text (HarfBuzz doesn't do this itself)
- [ ] provide option to render vertical text.

**Comment by alcinnz** [comment]
Preparing to tackle #11, Harfbuzz explicitly states it expects it's character input to be laidout in a consistant text direction. Even if it mixes left-to-right & right-to-left languages. We'll either need to implement the Unicode Bidi Algorithm ourselves or find someone else who has implemented it in Haskell.

Doesn't make a difference to what's needed for vertical text.

**Comment by lokedhs** [comment]
The bidi algorithm isn't very difficult to implement. It's mainly a question of following the steps outlined in the Unicode document: https://www.unicode.org/reports/tr9/

A simple implementation in Common Lisp (based on an implementation in Elisp) is here. It's a very straightforward implementation that may be useful as a reference if you want to implement it: https://github.com/McCLIM/McCLIM/blob/master/Backends/CLX/bidi.lisp

**Comment by alcinnz** [comment]
Upon asking questions about some of the test files I've gathered to help me guage Typograffiti's internationalization support, I am informed horizontal-exclusive scripts are very rare nowadays. It'd be good to offer an API to render text vertical for (mostly asian) cultures which do that, but it'd be reasonable to default to horizontal.

I think I can split this up into 2 subissues: allowing mixing left-to-right & right-to-left, and to provide an option for vertical rendering.

**Comment by alcinnz** [comment]
I'll assume what I get with Harfbuzz is sufficient for an 80% usecase, multilingual usecases can be addressed with a larger stack.
