### ISSUE TITLE
Support tabs

### ISSUE THREAD

**Issue by alcinnz** [schell/typograffiti#13]
Tab characters serve to add enough whitespace to reach the next "tabstop", which I've seen other text rendering libraries expose as a configurable parameter. The default is usually increments of 8 spaces, though that's ugly enough it frequently leads developers to shun tabs.

As-is Typograffiti doesn't do anything special upon encountering a tab character.

**Comment by alcinnz** [comment]
This is in the fancy branch (maybe you should reconfigure the default branch @schell ?).

Quite rudimentary as it operates in terms of a constant number of spaces, but should be serviceable for an 80% usecase as I address the other 20% in a fancier stack.

**Comment by schell** [comment]
I suggest merging `fancy` into `master` :)

**Comment by alcinnz** [comment]
O.K., that'd have to be a force-push. There's no recorded shared history between them.

**Comment by schell** [comment]
No worries, this is your project now :)

**Comment by alcinnz** [comment]
Turns out GitHub refuses to let me force-push to "master", and I don't have access to the settings panel to reconfigure the default branch. So I'd appreciate if you switched the default branch for me.

That said, I did save the old "master" branch aside in a new "modular" branch. (incidentally it'd be interesting to study how my work compares to that one...)

**Comment by schell** [comment]
It's now switched! Let me know if you want it switched again later. Maybe something like `main`?

**Comment by alcinnz** [comment]
Cool! Thanks! I've got a "main" branch now. That may be a nicer name longterm...

**Comment by schell** [comment]
Switched to `main` :)
