### ISSUE TITLE
Support bold, italics, etc OR Allow using externally-opened FreeType fonts

### ISSUE THREAD

**Issue by alcinnz** [schell/typograffiti#8]
For an app I am building I need the ability to apply bold, italics, etc style to externally-specified fonts regardless of whether the font provides them or not. I'll be using FontConfig to locate which fontfiles to load, so it may be convenient for me to load & configure a font via FreeType myself externally & hand that to Typograffiti.

There's also the question of whether you want to support underline/strikethrough/etc, but I'll be happy implementing those myself atop Typograffiti.

I'll be happy to contribute this feature myself, but first I want to ask for your design thoughts?

**Comment by schell** [comment]
I think anything that works is good enough! Thank you for offering to contribute, I can't wait to see what you come up with :)

**Comment by alcinnz** [comment]
To be clear: Should I work on the "gitlab" branch as opposed to "master"? That looks closer to what's uploaded to hackage.

Hmmmm... Struggling to build Typograffiti with stack. It keeps reporting:

> AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

**Comment by schell** [comment]
Hrm, yeah that's tough - I'm not sure which commit I left off at. I'll have to figure that out.

**Comment by alcinnz** [comment]
If it helps: the last commit of "master" is on May 11, 2019. The last commit of "gitlab" is on Jan 25th, 2019.

**Comment by schell** [comment]
Whichever one compiles and works as you expect. I think I'll simply push your branch as the new `main` when you're done. Feel free to make whatever changes you like.

**Comment by alcinnz** [comment]
I've prepared a low-level API that allows me to "register" caller-configured fontfiles under textual keys (same field as filepath). I plan to implement FontConfig bindings with conversion to a FreeType result, to abstract away the very concept of fontfiles, seperately.

Now I think I'll design then implement a highlevel API wrapping FreeType's `FT_Outline/Bitmap_Embolden/Transform` for bold & oblique software transforms. Or probably would offload the bitmap oblique operation onto the transformation matrix already being applied...

**Comment by alcinnz** [comment]
I recently merged this pull request.
